"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test111 import utils
from test111.types import BaseModel


class APIErrorUnauthorizedData(BaseModel):
    status: int

    error: str


class APIErrorUnauthorized(Exception):
    r"""Unauthorized error"""

    data: APIErrorUnauthorizedData

    def __init__(self, data: APIErrorUnauthorizedData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, APIErrorUnauthorizedData)
